# Model scope

## Energy Sector

The [energy sector](mod_energy) is fully integrated with the rest of the economy.
It is distinguished in an electric sector, a transportation sector, and an aggregated non-electric (industry, services and residential) sectors.

The primary and secondary forms of energy are

 | Primary Energy | Secondary Energy | 
 | -------------- | -----------      | 
 | Coal           | Electricity      | 
 | Oil            |                  | 
 | Gas            |                  | 
 | Uranium        |                  | 
 | Bioenergy      |                  |


Folowing power plant techonologies are included:

| Power plant                    |
| -----------                    | 
| Coal with and without CCS      | 
| Oil without CCS                | 
| Gas with and without CCS       | 
| Wind onshore and offshore      | 
| Solar PV and CSP               | 
| Nuclear LWR and advanced       | 
| Bioenergy with and without CCS | 
| Hydro power                    | 

Technologies that are subject to endogenous technological change are: advanced biomass, wind, solar, advanced nuclear. Overall energy efficiency is also subject to endogenous technical change.

## Land Use Sector

The [land use](mod_landuse) sector is represented in the WITCH model through a soft-linkage with the [GLOBIOM](http://www.globiom.org/) land use and forestry model.
[GLOBIOM](http://www.globiom.org/) is emulated via a response function
obtained from a large number of scenarios varying the price of biomass (both residues and plantations) and the price of carbon emission from land-use and agriculture.
[GLOBIOM](http://www.globiom.org/) also provides to WITCH the quantity of biomass, the CO~2~ emissions from deforestation and afforestation, CH~4~ and N~2~O emissions from agriculture.


## Greenhouse gases and air pollutants

The model computes many emissions species,
either directly, or assuming exogenous assumptions.
Mitigation can happen through technology substitution or storage,
direct abatement via MAC or end of pipe measures via emission factors.

 | Emissions | Source               | Mitigation           | 
 | ---       | ------               | ----------           | 
 | CO~2~     | Endogenous           | Substitution/Storage | 
 | CH~4~     | Partially endogenous | Substitution/MAC     | 
 | N~2~O     | Partially endogenous | Substitution/MAC     | 
 | F-gases   | Exogenous            | MAC                  | 
 | SO2       | Partially endogenous | Emissions factors    | 
 | VOC       | Partially endogenous | Emissions factors    | 
 | NOx       | Partially endogenous | Emissions factors    | 
 | BC        | Partially endogenous | Emissions factors    | 
 | OC        | Partially endogenous | Emissions factors    | 
 | CO        | Partially endogenous | Emissions factors    | 
 | NH~3~     | Exogenous            | RCP database         | 

## Regions

The original version of the model has 13 regions consistent on the basis of
geography, income and the structure of energy demand.


 | Region  | Countries                                           | 
 | ------  | ---------                                           | 
 | cajaz   | Canada, Japan, New Zeland                           | 
 | china   | China and Taiwan                                    | 
 | easia   | South East Asia, including Indonesia                | 
 | india   | India                                               | 
 | kosau   | South Korea, South Africa, Australia                | 
 | laca    | Latin America, Mexico and Caribbean                 | 
 | mena    | Middle East and North Africa                        | 
 | neweuro | EU new countries                                    | 
 | oldeuro | EU old countries (EU-15) + EFTA                     | 
 | sasia   | South Asia  (excluding India)                       | 
 | ssa     | Sub Saharan Africa                                  | 
 | te      | Non-EU Eastern European countries, including Russia | 
 | usa     | United States of America                            | 

## Coalitions


WITCH features any regional cooperations in the so-called coalitions.
By default, some coalitions are already defined:

*  no-cooperation : each region is mapped to a coalition containing only this region.

*  full-cooperation: the Grand Coalition containing all the world regions.
    
Coalitions and regions interact with each other because of the presence of economic
(technology, exhaustible natural resources) and environmental global externalities.

For each coalition a forward-looking agent
maximizes its own inter-temporal social welfare function, strategically and
simultaneously to other regions.

The inter-temporal equilibrium is calculated as an open-loop Nash equilibrium, but a
cooperative solution can also be implemented. More precisely, the Nash
equilibrium is the outcome of a non-cooperative, simultaneous, open membership game with full
information. Through the optimization process regions choose the optimal dynamic path of a set of control variables, namely investments, primary energy supply, oil market price and permit market price.

## Temporal process

The base year is 2005. The time horizon is 150 years, with 30 periods of 5-year time step. Longer time horizon can also be run until 2300 to avoid any end-of-horizon effect, but 2150 is generally sufficient.
Results are usually reported for the period 2005-2100 and the periods 2005, 2010 and 2015 are calibrated to the energy and economical statistics when available.
