# Energy module

WITCH includes a wide range of technology options to
describe the final use of energy and the generation of electricity.
The energy sector is described by a production function that aggregates
different factors at various levels and with associated elasticities of substitution $\rho$.
The main distinction is among electric generation and non-electric
consumption of energy. 

All the main technology features are represented:
yearly utilisation factors, fuel efficiencies, investment, and
operation and maintenance costs.


## Electric energy technology sectors

 

Electricity is generated by a series of traditional fossil fuel-based
technologies and carbon-free options.
Fossil fuel-based technologies include natural gas combined cycle (NGCC),
fuel oil and pulverised coal (PC) power plants.
Coal-based electricity can also be generated using IGCC production with CCS.
Low carbon technologies include hydroelectric and nuclear power,
renewable sources such as wind turbines and photovoltaic panels (wind and solar)
and two breakthrough technologies. 

The cost of electricity generation is endogenous and it combines capital costs,
O&M expenditure and the expenditure for fuels.

### Capital accumulation for electric energy technology sectors

[Eq. **eqk_en**]
The capital of some electricity production technologies accumulates as follows:

$$
   K_j(t+1,n) = K_j(t,n)\left(1-\delta_j(t+1,n)\right)^{\Delta_t} +
                \Delta_t \times \frac{I_j(t,n)}{SC_j(t,n)}, \forall j\in \mathcal{J}_{inv},
$$
where $\mathcal{J}_{inv}$ is the set of electric energy technology sectors in which one can invest.
The investment cost $SC$  for solar and wind energy is 
decreasing with the world cumulative installed capacity by means of
Learning-by-Doing.
On the other hand the investment costs $SC$  for backstop technologies are computed using Two Factor Learning Curve: costs reductions are driven by both, growth in cumulated installed capacity and accumulation of R&D knowledge.\\
The aforementioned methodology is shown in [Research and Development](mod_knowledge)\\

 | Symbol          | Definition                 | GAMS                     | Unit  | 
 | ------          | ----------                 | ----                     | ----  | 
 | $I_j(t,n)$      | Investment in energy tech. | "I_EN(jinv,t,n)"   | T$    | 
 | $K_j(t,n)$      | Capital in energy tech.    | "K_EN(j,t,n)"      | TW    | 
 | $SC_j(t,n)$     | Average investment cost    | "MCOST_INV(j,t,n)" | T$/TW | 
 | $\delta_j(t,n)$ | depreciation rate          | "delta(j,t,n)"     |       | 

### Production in electric sector

[Eq. **eqq_el**] 
[Eq. **eqq_el2**]
[Eq. **eqq_elff**] The CES top-tree for the electricity production sector is 
defined by the three following equations:

$$
    EL(t,n) = EL2(t,n) + \alpha_{el_{hydro}}(n) EL_{hydro}(t,n)
$$

$$
    EL2(t,n) = \phi_{el2}(n) \left( 
                           \alpha_{el2}(n) ELFF(t,n)^{\rho_{el2}(n)} +
                           \beta_{el2}(n) EL_{nucback}(t,n)^{\rho_{el2}(n)} +
                           \gamma_{el2}(n) EL_{intren}(t,n)^{\rho_{el2}(n)}
                           \right)^{\frac{1}{\rho_{el2}}(n)}
$$

$$
    ELFF(t,n) = \phi_{elff}(n) \left( 
                           \alpha_{elff}(n) EL_{coalwbio}(t,n)^{\rho_{elff}(n)} +
                           \beta_{elff}(n) EL_{oil}(t,n)^{\rho_{elff}(n)} +
                           \gamma_{elff}(n) EL_{gas}(t,n)^{\rho_{elff}(n)}
                           \right)^{\frac{1}{\rho_{elff}}(n)}
$$

 | Symbol               | Definition                                | GAMS                               | Unit       | 
 | ------               | ----------                                | ----                               | ----       | 
 | $EL(t,n)$            | Electric sector aggregate                 | "Q('el',t,n)"                | Trillion $ | 
 | $EL2(t,n)$           | Electric sector aggregate  (w/o hydro)    | "Q('el2',t,n)"               | Trillion $ | 
 | $EL_{coalwbio}(t,n)$ | Coal & wood biomass power plant aggregate | "Q('coalwbio',t,n)"          | Trillion $ | 
 | $EL_{gas}(t,n)$      | Gas power plant sector                    | "Q('gas',t,n)"               | Trillion $ | 
 | $EL_{hydro}(t,n)$    | Hydroelectric sector                      | "Q('ces_elhydro',t,n)"       | Trillion $ | 
 | $EL_{intren}(t,n)$   | Intermittent renewable aggregate          | "Q('ces_elintren',t,n)"      | Trillion $ | 
 | $EL_{nucback}(t,n)$  | Nuclear and backstop aggregate            | "Q('ces_elnuclearback',t,n)" | Trillion $ | 
 | $EL_{oil}(t,n)$      | Oil power plant sector                    | "Q('oil',t,n)"               | Trillion $ | 
 | $ELFF(t,n)$          | Fossil-fuel power plants aggregate        | "Q('elff',t,n)"              | Trillion $ | 


## Non-electric energy technology sectors

Energy consumption in the non-electric sector is based on traditional fuels
(traditional biomass, oil, gas and coal) and bio-fuels.
In order to account for food security concerns, overall penetration of
bio-fuels is assumed to remain modest over the century.
The consumption of oil can be substituted with a carbon-free backstop
technology, which could be thought of as next generation bio-fuels or
carbon-free hydrogen.
As a consequence, the backstop technology is mostly conceived as an
abatement option for the transport sector. 

### Production in the non-electric sector

[Eq. **eqq_nel**] 
[Eq. **eqq_nelog**]
The CES tree for the non-electric energy technology sector is 
defined by the two following equations:

$$
    NEL(t,n) = \alpha_{nel_{coal}} NEL_{coal}(t,n) +
             NEL_{log}(t,n) +
             \alpha_{nel_{trbiomass}} NEL_{trbiomass}(t,n) 
$$

$$
    NEL_{log}(t,n) = \phi_{nelog}(n) \left( 
                           \alpha_{nelog}(n) NEL_{oilback}(t,n)^{\rho_{nelog}(n)} +
                           \beta_{nelog}(n) NEL_{gas}(t,n)^{\rho_{nelog}(n)} +
                           \gamma_{nelog}(n) NEL_{trbiofuel}(t,n)^{\rho_{nelog}(n)}
                           \right)^{\frac{1}{\rho_{nelog}}(n)}
$$

 | Symbol                 | Definition                              | GAMS                             | Unit      | 
 | ------                 | ----------                              | ----                             | ----      | 
 | $NEL(t,n)$             | Non-electric sector aggregate           | "Q('nel',t,n)"             | Trillon $ | 
 | $NEL_{coal}(t,n)$      | Energy in Coal sector                   | "Q_EN('nelcoal',t,n)"      | TWh       | 
 | $NEL_{log}(t,n)$       | Other non-electric sector aggregate     | "Q('nelog',t,n)"           | Trillon $ | 
 | $NEL_{trbiomass}(t,n)$ | Energy in traditional biomass sector    | "Q_EN('neltrbiomass',t,n)" | TWh       | 
 | $NEL_{oilback}(t,n)$   | Energy in oil and backstop non-electric | "Q_EN('neloilback',t,n)"   | TWh       | 
 | $NEL_{gas}(t,n)$       | Energy in gas sector                    | "Q_EN('nelgas',t,n)"       | TWh       | 
 | $NEL_{trbiofuel}(t,n)$ | Energy in Traditional biofuel           | "Q_EN('neltrbiofuel',t,n)" | TWh       | 

## Primary Energy Supply

[Eq. **eqq_pes**]
The total primary energy supply is the sum of the consumption from all the sectors.  

$$
    Q_f(t,n) = \sum_j Q_{j,f}(t,n)
$$

 | Symbol         | Definition                               | GAMS                     | Unit | 
 | ------         | ----------                               | ----                     | ---- | 
 | $Q_f(t,n)$     | Total amount of fuel consumed            | "Q_PES(f,t,n)"     | TWh  | 
 | $Q_{j,f}(t,n)$ | Total amount of fuel consumed per sector | "Q_IN(f,jfed,t,n)" | TWh  | 

## Trade balance of energy

[Eq. **eq_mkt_clearing**]
The consumption of fuel $f$, $Q_f$, and
either domestic extraction or imports,
$X_{f}$ are balanced at the world level. 

$$
    \sum_n Q_f(t,n) = \sum_n X_f(t,n)
$$

 | Symbol     | Definition                     | GAMS                 | Unit | 
 | ------     | ----------                     | ----                 | ---- | 
 | $Q_f(t,n)$ | Total amount of fuel consumed  | "Q_PES(f,t,n)" | TWh  | 
 | $X_f(t,n)$ | Total amount of fuel extracted | "Q_OUT(f,t,n)" | TWh  | 

 1.  If the country is a net exporter, $X_f$ is negative.
 2.  In the current version, the fuel trades happen only for oil.

## Fuel Cost

[Eq. **eqcost_pes**]
The net cost of Primary Energy Supplies (PES) is equal to the
cost of consumed fuels minus the cost of extracted fuels

$$
	C_f(t,n) = MC_f(t,n) \times Q_f(t,n) -
	              p_f(t) \times X_f(t,n)
$$

 | $C_f(t,n)$  | Primary Energy Supplies cost            | "COST_PES(f,t,n)"  | T$     | 
 | ----------  | ----------------------------            | -----------------------  | --     | 
 | $MC_f(t,n)$ | Average cost of Primary Energy Supplies | "MCOST_PES(f,t,n)" | T$/TWh | 
 | $Q_f(t,n)$  | Total amount of fuel consumed           | "Q_PES(f,t,n)"     | TWh    | 
 | $X_f(t,n)$  | Total amount of fuel extracted          | "Q_OUT(f,t,n)"     | TWh    | 
 | $p_f(t,n)$  | World market fuel prices                | "FPRICE(f,t)"      | T$/TWh | 

The price of fossil fuels and exhaustible resources (oil, gas, coal and
uranium) is determined by the marginal cost of
extraction, which in turn depends on current and cumulative
extraction, plus a regional mark-up to mimic different regional costs.

## Additional constraints

### Constraint on the electric production capacity

[Eq. **eqq_en_mu**]
In the electric sector, the production capacity is bounded by the capital stock adjusted by the coefficient $\mu$ (**mu**).

$$
    EL_j(t,n) \le \mu_j(t,n) \times KEL_j(t,n)
$$

 | Symbol       | Definition                            | GAMS                  | Unit   | 
 | ------       | ----------                            | ----                  | ----   | 
 | $EL_j(t,n)$  | Electric production capacity          | "Q_EN(jel,t,n)" | TWh    | 
 | $KEL_j(t,n)$ | Capital in electric production        | "K_EN(jel,t,n)" | TW     | 
 | $\mu_j(t,n)$ | Capacity factor of maximum production | "mu(jel,t,n)"   | TWh/TW | 

### Constraint on new capacity of electric backstop

Breakthrough in power generation technologies is modelled by introducing
a backstop technology, that can be better thought of as a compact
representation of a portfolio of advanced technologies that can
substitute nuclear power.
[Eq. **eqq_en_lim_elback**] 
The share of new production capacity of the technology "Electric backstop" is bounded by the coefficient **lim_elback** = 5%. 

$$
       EL_{elback}(t+1,n) - EL_{elback}(t,n) \le lim\_elback \times \left( EL(t,n) - EL_{elback}(t,n) \right)
$$

 | Symbol             | Definition                 | GAMS                       | Unit | 
 | ------             | ----------                 | ----                       | ---- | 
 | $EL_{elback}(t,n)$ | Electric backstop capacity | "Q_EN('elback',t,n)" | TWh  | 
 | $KEL_j(t,n)$       | Total electric capacity    | "Q_EN('el',t,n)"     | TWh  | 


## Efficiency of the energy technology sectors

[Eq. **eqq_en_in**]
The production capacity is equal to the energy consumed times the overall efficiency ratio of the sector $\xi$ (**csi**).

$$
    Q_j(t,n) = \sum_f \xi_{j,f}(t,n) \times Q_{j,f}(t,n)
$$

 | Symbol           | Definition                         | GAMS                     | Unit    | 
 | ------           | ----------                         | ----                     | ----    | 
 | $Q_j(t,n)$       | Production capacity                | "Q_EN(jfed,t,n)"   | TWh     | 
 | $Q_{j,f}(t,n)$   | Amount of fuel consumed per sector | "Q_IN(f,jfed,t,n)" | TWh     | 
 | $\xi_{j,f}(t,n)$ | Sector efficiency ratio            | "csi(f,jfed,t,n)"  | TWh/TWh | 

## Energy tree

[Eq. **eqq_en_tree**]
Ensure that the production capacity are consistent at each levels of the energy tree.

$$
    Q_j(t,n) = \sum_{j'\in succ(j)} Q_{j'}(t,n),
$$
where $succ(j)$ are the successors of $j$ in the energy tree.

 | Symbol     | Definition          | GAMS                | Unit | 
 | ------     | ----------          | ----                | ---- | 
 | $Q_j(t,n)$ | Production capacity | "Q_EN(j,t,n)" | TWh  | 

