# Emissions and the climate
 
## Greenhouse gas emissions

### CO~2~ emissions

Total CO~2~ emissions are the sum of CO~2~ emissions from fossil-fuel and industry and from land-use change
minus emissions from avoided deforestation


$$
    Q_{CO2}(t,n) = Q_{CO2ind}(t,n) + Q_{CO2lu}(t,n) - Q_{redd}(t,n)
$$

Emissions from land-use change (and REDD) are provided by the [land-use](mod_landuse) module.

CO~2~ emissions from fossil-fuel and industry are the energy consumed multiplied the stochiometric coefficient **emi_sf** plus the emissions from extraction minus stored emissions.
$$
    Q_{CO2ind}(t,n) = \sum_f \left( emi_st(f)\times Q_f(t,n) \right) +
                      \sum_f EX_f(t,n) -
                      Q_{CCS}(t,n)
$$


### Other greenhouse gas emissions

The other Kyoto greenhouse gases are CH4, N2O, short-lived and long-lived F-gases.

$$
    Q_{oghg}(t,n) = emi\_baseline(oghg,t,n) \times (1 - ABAT(oghg,t,n) \times emi\_abat\_max(oghg,t,n))
$$

$emi\_abat\_max$ is the maximum possible abatment expressed as a share of baseline emissions ($emi\_baseline$). The baseline emissions are following the [ EPA projections](http://www.epa.gov/climatechange/EPAactivities/economics/nonco2projections.html).

### Carbon market clearing

Globally, the sum of regional net import carbon permits 
has to be equal to zero.

$$
    \sum_n Q_{nip}(n,t) = 0
$$

### Emission costs

The CO~2~ emission costs are equal 
to the carbon permit price times the amount of net import of carbon permits.

$$
    C_{CO2}(n,t) = p_{nip}(n,t) \times Q_{nip}(n,t)
$$

The non-CO~2~ GHG emission costs are based on marginal abatement curves.

\begin{align*}
    C_{e}(n,t) =& ref_e(n,t) \times \overline{abat}_e(n,t) \times
                 \left(
                    a_e \times ABAT_e(n,t) +
                    \frac{b_e}{c_e} \times 
                    \exp\left(
                          c_e \times ABAT_e(n,t) - 1
                        \right)
                 \right), \\& \forall e \in \{CH_4, N_2O, slf, llf\}
\end{align*}
where $a_e$, $b_e$ and $c_e$ are the coefficient of
the  marginal abatement curves.


The cost of the CCS is computed as

$$
    C_{e}(n,t) = C_{CCS}(n,t) \times Q_{e}(n,t), \forall e \in \{CCS\}
$$

$C_{CCS}$ is computed in the [carbon capture and storage](mod_ccs) module.


### Bank and borrowing

Permit emission savings are the sum of existing savings plus net emission savings

$$
    M_{SAV}(t+1,n) = M_{SAV}(t,n) + \Delta_t \times Q_{SAV}(t,n)
$$

To avoid speculation,
emission savings are bounded by net import of carbon permits.
(only when the global variable **non_speculation** is set to true)  

$$
    Q_{SAV}(t,n) \le  bigM \times \left( |Q_{nip}(t,n)| - Q_{nip}(t,n) \right)
$$

$bigM$ is a very high level maximum trade of emissions. 

