# Static calibration

This section explains the code contained in
'' data/static_calibration.gms ''. By executing this file a static
calibration gdx will be produced, including all the coefficients for
the WITCH production functions computed to reproduce historically
observed values in the calibration year (i.e. 2005).  Since static
calibration is repeated for each region independently, the index on
region will be dropped on any symbol introduced in this section.

## Nodes

The nest of WITCH production functions can be thought as a tree of
nodes. The set of nodes considered in the static calibration is
detailed below. 

 | Node name in GAMS   | Parent node    | Node represents                                                     | 
 | -----------------   | -----------    | ---------------                                                     | 
 | '' yces ''          |                | economic output / final good                                        | 
 | '' kl ''            | '' yces ''     | capital and labour aggregate                                        | 
 | '' fen ''           | '' yces ''     | final energy                                                        | 
 | '' k ''             | '' kl ''       | capital net of energy capital                                       | 
 | '' l ''             | '' kl ''       | labour                                                              | 
 | '' krd_en ''        | '' fen ''      | stock of energy efficiency knowledge                                | 
 | '' en ''            | '' fen ''      | energy                                                              | 
 | '' nel ''           | '' en ''       | non-electric energy                                                 | 
 | '' el ''            | '' en ''       | electricity                                                         | 
 | '' elhydro ''       | '' el ''       | electricity from hydroelectric plants                               | 
 | '' el2 ''           | '' el ''       | electricity net of hydroelectric generation                         | 
 | '' elffren ''       | '' el2 ''      | electricity from fossil fuels and intermittent renewables aggregate | 
 | '' elnuclearback '' | '' el2 ''      | electricity from traditional and advanced nuclear plants            | 
 | '' elff ''          | '' elffren ''  | electricity from fossil fuels                                       | 
 | '' elintren ''      | '' elffren ''  | electricity from intermittent renewables                            | 
 | '' elwind ''        | '' elintren '' | electricity from wind                                               | 
 | '' elpv ''          | '' elintren '' | electricity from solar PV                                           | 
 | '' elcsp ''         | '' elintren '' | electricity from solar CSP                                          | 
 | '' elcoalwbio ''    | '' elff ''     | electricity from pulverized and ICCG coal- and biomass-fired plants | 
 | '' eloil ''         | '' elff ''     | electricity from oil plants                                         | 
 | '' elgas ''         | '' elff ''     | electricity from gas plants                                         | 
 | '' nelcoal ''       | '' nel ''      | non-electric coal energy                                            | 
 | '' neltrbiomass ''  | '' nel ''      | non-electric traditional biomass energy                             | 
 | '' nelog ''         | '' nel ''      | non-electric oil/gas/biofuel energy aggregate                       | 
 | '' neloil ''        | '' nelog ''    | non-electric oil and advanced biofuels energy aggregate             | 
 | '' nelgas ''        | '' nelog ''    | non-electric gas energy                                             | 
 | '' neltrbiofuel ''  | '' nelog ''    | non-electric traditional biofuels energy                            | 

Most nodes have a corresponding entry in the '' Q '' variable in the main
code. The exceptions are:

*  non-electric energy leaf nodes, mapped to entries in variable '' Q_EN '';

*  '' l '', mapped to parameter '' l '';

*  '' k '', mapped to variable '' K('fg') '';

*  '' krd_en '', mapped to variable '' K_RD('en') ''.

## Technologies and fuels

Energy leaf nodes corresponds to either single technologies with the
same name (e.g. node '' elpv '' just represents technology '' elpv '') or
multiple technologies. The latter ones are detailed below.

 | Leaf node           | Technologies                                           | Description                                        | 
 | ---------           | ------------                                           | -----------                                        | 
 | '' elwind ''        | '' elwindon '', '' elwindoff ''                        | Wind onshore and offshore                          | 
 | '' elnuclearback '' | '' elnuclear_new '', '' elnuclear_old '', '' elback '' | New and old traditional nuclear + adv. nuc. plants | 
 | '' elhydro ''       | '' elhydro_new '', '' elhydro_old ''                   | New and old hydroelectric plants                   | 
 | '' elcoalwbio ''    | '' elpc_new '', '' elpc_old '', '' elcigcc ''          | New and old pulverized + ICCG coal-fired plants    | 
 | "                   | '' elpb_new '', '' elpb_old '', '' elbigcc ''          | New and old pulverized + ICCG biomass-fired plants | 
 | '' eloil ''         | '' eloil_new '', '' eloil_old ''                       | New and old oil power plants                       | 
 | '' elgas ''         | '' elgastr_new '', '' elgastr_old '', '' elgasccs ''   | New and old traditional + w/ CCS gas plants        | 

Technologies may be fueled by one of these resources \(f\): oil, coal
gas, uranium, traditional biofuel ('' trbiofuel '') or traditional biomass
('' trbiomass '').
## Variables and parameters

The symbols used for static calibration are introduced below. Data for
input symbols are collected from various sources.

 | Symbol                 | Definition                                                        |                 | GAMS                   | 
 | ------                 | ----------                                                        |                 | ----                   | 
 | $\(P_{0,i}\)$            | Price at calibration year \(\forall\) node \(i\)                  | see table below | '' P0(node,n) ''       | 
 | $\(Q_{0,i}\)$            | Quantity at calibration year \(\forall\) node \(i\)               | see table below | '' Q0(node,n) ''       | 
 | $\(\alpha_i\)$           | Coefficient multiplying factor at node \(i\)                      | unitless        | '' ALPHA(node,n) ''    | 
 | $\(R\)$                  | Interest rate                                                     | unitless        | '' R(node,n) ''        | 
 | $\(\delta_{\text{FG}}\)$ | Depreciation of final good capital                                | unitless        | '' delta0('fg') ''     | 
 | $\(\delta_{\text{RD}}\)$ | Depreciation of stock of knowledge in en.eff.                     | unitless        | '' delta_rd('en') ''   | 
 | $\(\delta_j\)$           | Depreciation of capital for plant of tech \(j\)                   | unitless        | '' delta_en0(jel,n) '' | 
 | \(SC_{0,j}\)           | Average cost of investment for tech \(j\)                         | T$/TW           | '' mcost_inv0(jel,n '' | 
 | $\(K_{0,j}\)$            | Initial capacity for tech \(j\)                                   | TW              | '' k_en0(jel,n) ''     | 
 | $\(\mu_{0,j}\)$          | Capacity factor of max production of tech \(j\)                   | TWh/TW          | '' mu0(jel,n) ''       | 
 | $\(oem_{0,j}\)$          | Cost of operation and mantainance of tech \(j\)                   | T$/TW           | '' oem0(jel,n) ''      | 
 | $\(\xi_{0,f,j}\) $       | Efficiency of using fuel \(f\) in tech \(j\)                      | TWh/TWh         | '' csi0(f,jel,n) ''    | 
 | \(FC_{0,f}\)           | Cost of fuel                                                      | T$/TWh          | '' fcost(f,n) ''       | 
 | \(\rho_i\)             | 1/1-\(\rho\) is the elasticity of substitution for CES node \(i\) | unitless        | '' calirho(node) ''    | 
 | \(\phi\)               | Crowding out factor for investments in R&D (equal to 4)           | unitless        | '' rd_crowd_out ''     | 
 | \(\Delta_t\)           | Model time step (equal to 5)                                      | year            | '' tstep ''            | 

In the standard setup, all symbols take fixed values, and are thus
considered inputs to the static calibration problem, apart from:

*  \(Q_{0,i}\) of '' k '' and parent nodes (except '' yces '');

*  \(\alpha_i\) of all nodes (except '' yces '');

The values of these
outputs are obtained from the initializations and the system of
equations described further on.

The unit of \(P_{0,i}\) and \(Q_{0,i}\) depends on \(i\).
 | Node                     | Unit of \(P_{0,i}\) | Unit of \(Q_{0,i}\) | 
 | ----                     | ------------------- | ------------------- | 
 | parent                   | unitless            | T$                  | 
 | energy leaf              | T$/TWh              | TWh                 | 
 | '' l ''                  | T$/Million people   | Million people      | 
 | '' k '' and '' krd_en '' | unitless            | T$                  | 
## Initializations and assumptions

### Quantities


*  Parent nodes have quantities measuring the values of their production subtrees in T$.

*  '' yces '' quantity is the GDP in 2005 net of oil extraction revenues.

*  Leaf nodes quantities are fixed to their 2005 values, with the following remarks:
    * '' elwind '', '' elpv '' and '' elcsp '' use 2015 values;
    * '' neltrbiofuel '' has value 0, as it is now controlled in the transport module and not via the CES any more;
    * '' neloil '' is net of the oil used in traditional cars, as this is now explicitly accounted in the transport module.
### Prices


*  Parent nodes have a unitary reference price.

*  Electricity leaf nodes have prices defined in the equations below. In the standard setup they are constant.

*  Non-electric energy leaf nodes have a price equal to the \(FC_{0,f}\) of the their corresponding fuel \(f\), which in turn are equal to a world price plus a regional markup.

*  Price of labour is assumed to be a constant fraction of the GDP per capita: $$ P_{0,L} = 0.7 \frac{Q_{0,\text{YCES}}}{Q_{0,l}} $$.

*  Prices for '' elwind '', '' elpv '' and '' elcsp '' refer to 2015 values instead of 2005 values.
## Equations

### Main equations

The use of production functions in their so-called Calibrated Share
Form allows for a very simple formulation of the calibration problem,
requiring at its core just two classes of equations (see [[http://www.gamsworld.org/mpsge/debreu/ces.pdf|Lecture Notes
on Constant Elasticity Functions]] by T. Rutherford).

Quantities of parents are expressed in terms of values of children via
the **Euler's** homogeneous function **theorem** (degree 1) ('' eq_euler '').
$$ Q_{0,i} = \sum_{i' \text{ child of } i} Q_{0,i'} P_{0,i'} \qquad \forall \text{ node }i
\text{ with children nodes} $$

Production functions **value shares** are the fraction of value of the
child node with respect to the value of the parent node ('' eq_value_shares '').
$$ \alpha_{0,i} = P_{0,i} Q_{0,i} / Q_{0,i'} \qquad \forall \text{ nodes }(i,i') \text{
s.t. } i \text{ is child of }i' $$
### Auxiliary equations

The following are trivial equations in the standard setup, but
become active part of the system with the '' use_capital '' flag.

The **price of capital of final good** is equal to the interest rate \(R\)
plus depriciation ('' eq_price_of_capital '').
$$ P_{0,\text{K}} = R + (1-(1-\delta_{\text{FG}})^{\Delta_t})/\Delta_t $$

The **price of capital of energy efficiency R&D** is the same as above
times the crowding out factor of R&D \(\phi\) ('' eq_price_of_capital_rnd '').
$$ P_{0,\text{KRD_EN}} =  \phi (R + (1-(1-\delta_{\text{RD}})^{\Delta_t})/\Delta_t) $$

The **price of electricity** for generation technologies without fuel
costs is given by the sum of the price of capital (dependant on the
unit cost of investment \(SC_0\)) and the unit cost of operation and
mantainance (\(oem_0\)), divided by the electricity produced per unit of
capital (i.e. the capacity factor \(\mu\)) ('' eq_price_of_electricity_not_fed '').

$$ P_{0,i} = \frac{(R + (1-(1-\delta_j)^{\Delta_t})/\Delta_t)*SC_{0,j} +
oem_{0,j}}{\mu_{0,j}} \qquad \forall \text { electric leaf node } i \text {
and corresponding tech } j$$

The price of electricity for generation technologies with fuel costs
('' eq_price_of_electricity_fed '') is the same above plus the unit cost of fuel divided by the the
fraction of fuel energy converted in electricity (i.e. the efficiency
\(\xi_0\)).

For those nodes corresponding to the linear combination of the output
of multiple power plants, and thus potentially with different
assumptions on depreciation and O&M, investment and fuel costs, a
weighted avarage on the capital is considered.
## Flags

### Interest rate as a variable

'' use_capital '' makes the following changes to the problem:

*  \(R\) becomes a variable;

*  \(Q_{0,k}\) is provided as an input;

*  the equations for calculating the prices which depend on \(R\) become
active part of the system;

*  the equation '' eq_interest_rate '' is added.
### Feedbacks

The flags '' transport_feedback '', '' extraction_feedback '' and
'' renewables_feedback '' allow to experiment with an iterative solution
to the calibration problem where the values for oil used in transport,
revenues from oil extraction and prices and quantities of renewables
in 2015 obtained from one static calibration is used to adjust the
input for the next iteration, until a certain convergence on the
variables is obtained.
## Output

After the solution of the system, and potential iterations if
feedbacks are active, all the symbols in the table of section
"Variables and parameters" are saved in '' data/%gdxout%.gdx ''. To
use this calibration gdx, run the model specifying its path
in the '' calibgdx '' flag.

